title: XRAI Keele
description: >- 
  A website for XRAI Keele.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xraikeele.github.io" # the base hostname & protocol for your site
theme: cayman
markdown: kramdown